name = "Calibration"
uuid = "c4a1b1f9-2dbe-4eda-9c4c-ed1f69dcbb3f"
authors = ["jungadam "]
version = "0.1.0"

[deps]
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
Atomix = "a9b6321e-bd34-4604-b9c9-b65b8de01458"
COSMO = "1e616198-aa4e-51ec-90a2-23f7fbd31d8d"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
CUDA_Driver_jll = "4ee394cb-3365-5eb0-8335-949819d2adfc"
CUDA_Runtime_Discovery = "1af6417a-86b4-443c-805f-a4643ffb695f"
CUDA_Runtime_jll = "76a88914-d11a-5bdc-97e0-2f5a05c973a2"
CUDSS = "45b445bb-4962-46a0-9369-b4df9d0f772e"
CalibrationTests = "2818745e-0823-50c7-bc2d-405ac343d48b"
Clarabel = "61c947e1-3e6d-4ee4-985a-eec8c727bd6e"
Convex = "f65535da-76fb-5f13-bab9-19810c17039a"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
EmpiricalCDFs = "0dcf7749-4f9f-5e13-9c57-506664207bbc"
GPUToolbox = "096a3bc2-3ced-46d0-87f4-dd12716f4bfc"
HypothesisTests = "09f84164-cd44-5f33-b23f-e6b0d136a0d5"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
KernelFunctions = "ec8451be-7e33-11e9-00cf-bbf324bd1392"
KrylovKit = "0b1a1467-8014-51b9-945f-bf0ae24f4b77"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MLJ = "add582a8-e3ab-11e8-2d5e-e98b27df1bc7"
MLJBase = "a7f614a8-145f-11e9-1d2a-a57a1082229d"
MadNLP = "2621e9c9-9eb4-46b1-8089-e8c72242dfb6"
MadNLPGPU = "d72a61cc-809d-412f-99be-fd81f4b8a598"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
NNlib = "872c559c-99b0-510c-b3b7-b6c96a88d5cd"
NVTX = "5da4648a-3479-48b8-97b9-01cb529c0a1f"
OMEinsum = "ebe7aa44-baf0-506c-a96f-8464559b3922"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
RollingFunctions = "b0e4dd01-7b14-53d8-9b45-175a3e362653"
SCS = "c946c3f1-0d1f-5ce8-9dea-7daa1f7e2d13"
SCS_GPU_jll = "af6e375f-46ec-5fa0-b791-491b0dfa44a4"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
TensorOperations = "6aa20fa7-93e2-5fca-9bc0-fbd0db3c71a2"
Tullio = "bc48ee85-29a4-5162-ae0b-a64e1601d4bc"

[compat]
Adapt = "4.3.0"
ArgParse = "1.2.0"
Atomix = "1.1.2"
COSMO = "0.8.9"
CUDA = "5.8.2"
CUDA_Driver_jll = "0.13.1"
CUDA_Runtime_Discovery = "0.3.5"
CUDA_Runtime_jll = "0.17.1"
CUDSS = "0.5.0"
CalibrationTests = "0.6.3"
Clarabel = "0.11.0"
Convex = "0.16.4"
Distances = "0.10.12"
Distributions = "0.25.120"
EmpiricalCDFs = "0.2.2"
GPUToolbox = "0.2.0"
HypothesisTests = "0.11.5"
Interpolations = "0.16.1"
JLD2 = "0.6.1"
KernelAbstractions = "0.9.38"
KernelFunctions = "0.10.65"
KrylovKit = "0.10.0"
LinearAlgebra = "1.11.0"
MLJ = "0.21.0"
MLJBase = "1.9.2"
MadNLP = "0.8.9"
MadNLPGPU = "0.7.11"
MathOptInterface = "1.42.1"
NNlib = "0.9.31"
NVTX = "1.0.1"
OMEinsum = "0.9.1"
Optim = "1.13.2"
Plots = "1.41.1"
Polynomials = "4.1.0"
Printf = "1.11.0"
ProgressMeter = "1.10.4"
Random = "1.11.0"
Revise = "3.9.0"
RollingFunctions = "0.8.1"
SCS = "2.1.0"
SCS_GPU_jll = "3.2.7"
SparseArrays = "1.11.0"
StatsBase = "0.34.6"
TensorOperations = "5.3.0"
Tullio = "0.3.8"
