[deps]
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
Atomix = "a9b6321e-bd34-4604-b9c9-b65b8de01458"
BlockDiagonals = "0a1fb500-61f7-11e9-3c65-f5ef3456f9f0"
COSMO = "1e616198-aa4e-51ec-90a2-23f7fbd31d8d"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
CUDA_Driver_jll = "4ee394cb-3365-5eb0-8335-949819d2adfc"
CUDA_Runtime_Discovery = "1af6417a-86b4-443c-805f-a4643ffb695f"
CUDA_Runtime_jll = "76a88914-d11a-5bdc-97e0-2f5a05c973a2"
CUDSS = "45b445bb-4962-46a0-9369-b4df9d0f772e"
Calibration = "c4a1b1f9-2dbe-4eda-9c4c-ed1f69dcbb3f"
CalibrationTests = "2818745e-0823-50c7-bc2d-405ac343d48b"
Clarabel = "61c947e1-3e6d-4ee4-985a-eec8c727bd6e"
Convex = "f65535da-76fb-5f13-bab9-19810c17039a"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DifferentiationInterface = "a0c0ee7d-e4b9-4e03-894e-1c5f64a51d63"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
DistributionsAD = "ced4e74d-a319-5a8a-b0ac-84af2272839c"
EmpiricalCDFs = "0dcf7749-4f9f-5e13-9c57-506664207bbc"
GPUToolbox = "096a3bc2-3ced-46d0-87f4-dd12716f4bfc"
Humanize = "7ec9b9c5-1998-51e1-b7fc-fc3590c18259"
HypothesisTests = "09f84164-cd44-5f33-b23f-e6b0d136a0d5"
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
KernelFunctions = "ec8451be-7e33-11e9-00cf-bbf324bd1392"
KrylovKit = "0b1a1467-8014-51b9-945f-bf0ae24f4b77"
Latexify = "23fbe1c1-3f47-55db-b15f-69d7ec21a316"
LoggingExtras = "e6f89c97-d47a-5376-807f-9c37f3926c36"
MCMCChains = "c7f686f2-ff18-58e9-bc7b-31028e88f75d"
MLJ = "add582a8-e3ab-11e8-2d5e-e98b27df1bc7"
MLJBase = "a7f614a8-145f-11e9-1d2a-a57a1082229d"
MadNLP = "2621e9c9-9eb4-46b1-8089-e8c72242dfb6"
MadNLPGPU = "d72a61cc-809d-412f-99be-fd81f4b8a598"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
MultivariateStats = "6f286f6a-111f-5878-ab1e-185364afe411"
NLopt = "76087f3c-5699-56af-9a33-bf431cd00edd"
NNlib = "872c559c-99b0-510c-b3b7-b6c96a88d5cd"
NVTX = "5da4648a-3479-48b8-97b9-01cb529c0a1f"
OMEinsum = "ebe7aa44-baf0-506c-a96f-8464559b3922"
Optimization = "7f7a1694-90dd-40f0-9382-eb1efda571ba"
OptimizationNLopt = "4e6fcdb7-1186-4e1f-a706-475e75c168bb"
ParametricDAQP = "19f72acb-e2a9-45c8-96b9-4d5487c8db2e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PlutoUI = "7f904dfe-b85e-4ff6-b463-dae2292396a8"
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
ProximalAlgorithms = "140ffc9f-1907-541a-a177-7475e0a401e9"
ProximalOperators = "a725b495-10eb-56fe-b38b-717eba820537"
QPDAS = "297e508c-b2a7-11e8-1524-5dccae6124f6"
RDatasets = "ce6b1742-4840-55fa-b093-852dadbb1d8b"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
RollingFunctions = "b0e4dd01-7b14-53d8-9b45-175a3e362653"
SCS = "c946c3f1-0d1f-5ce8-9dea-7daa1f7e2d13"
SCS_GPU_jll = "af6e375f-46ec-5fa0-b791-491b0dfa44a4"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
TensorOperations = "6aa20fa7-93e2-5fca-9bc0-fbd0db3c71a2"
TimeZones = "f269a46b-ccf7-5d73-abea-4c690281aa53"
Turing = "fce5fe82-541a-59a6-adf8-730c64b5f9a0"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"
